gitpath = "/home/jake/Build/dotfiles"

[[files]]
name = "bspwm"
origin = "/home/jake/Build/dotfiles/bspwm/bspwmrc"
deployed = "/home/jake/.config/bspwm/bspwmrc"

[[files]]
name = "stow-squid"
origin = "/home/jake/Build/dotfiles/stow-squid/stow-squid.toml"
deployed = "/home/jake/.config/stow-squid/stow-squid.toml"

[[files]]
name = "tmux"
origin = "/home/jake/Build/dotfiles/.tmux.conf"
deployed = "/home/jake/.tmux.conf"

[[files]]
name = "alacritty"
origin = "/home/jake/Build/dotfiles/alacritty/alacritty.yml"
deployed = "/home/jake/.config/alacritty/alacritty.yml"

[[files]]
name = "lev_bashrc"
origin = "/home/jake/Build/dotfiles/lev_bashrc"
deployed = "/home/jake/.bashrc"

[[files]]
name = "an_bashrc"
origin = "/home/jake/Build/dotfiles/an_bashrc"
deployed = "/home/jake/.bashrc"

[[files]]
name = "sxhkd"
origin = "/home/jake/Build/dotfiles/sxhkd/sxhkdrc"
deployed = "/home/jake/.config/sxhkd/sxhkdrc"

[[files]]
name = "nvim"
origin = "/home/jake/Build/dotfiles/nvim/init.vim"
deployed = "/home/jake/.config/nvim/init.vim"
