#! /bin/sh

sxhkd &
dunst &
picom &
xscreensaver &
polybar example &
redshift -P -O 3900 &

bash $HOME/.scripts/bspwmstartup

bspc config border_width         6
bspc config focused_border_color "#a2a2a2"
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Yad state=floating

(ps x | grep bspswallow | grep -v grep) || bspswallow &
