#! /bin/sh

sxhkd &
dunst -conf $HOME/.config/dunst/dunstrc &
picom &
xscreensaver &
polybar example &
# redshift -P -O 4600 &

bash $HOME/.scripts/startup bspwm

# betterlockscreen -u ~/.config/wallpaper/walls/ &

bspc config border_width         6
 
# bspc config focused_border_color "#3498db"
# bspc config focused_border_color "#d35400"
bspc config focused_border_color "#7c27a0"

bspc config window_gap           4
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Yad state=floating

(ps x | grep bspswallow | grep -v grep) || bspswallow &
